# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Inventory.create(price: 229, category: "New Items", description: "Atomic Skis")
Inventory.create(price: 250, category: "New Items", description: "K2 Skis")
Inventory.create(price: 260, category: "New Items", description: "Dynastar Skis")
Inventory.create(price: 275, category: "New Items", description: "Head Skis")
Inventory.create(price: 285, category: "New Items", description: "Line Skis")
Inventory.create(price: 290, category: "New Items", description: "Dynamic Skis")
Inventory.create(price: 229, category: "New Items", description: "Atomic Skis")
Inventory.create(price: 250, category: "New Items", description: "K2 Skis")
Inventory.create(price: 260, category: "New Items", description: "Dynastar Skis")
Inventory.create(price: 275, category: "New Items", description: "Head Skis")
Inventory.create(price: 285, category: "New Items", description: "Line Skis")
Inventory.create(price: 290, category: "New Items", description: "Dynamic Skis")
Order.create(customer:"Defualt", total: 1000)
Order.create(customer:"Defualt", total: 1000)
Order.create(customer:"Defualt", total: 1000)
Order.create(customer:"Defualt", total: 1000)
Order.create(customer:"Defualt", total: 1000)
LineItem.create(order_id: 1, inventory_id:2)
LineItem.create(order_id: 1, inventory_id:3)
LineItem.create(order_id: 1, inventory_id:4)
LineItem.create(order_id: 1, inventory_id:5)
LineItem.create(order_id: 1, inventory_id:6)
LineItem.create(order_id: 1, inventory_id:7)
LineItem.create(order_id: 1, inventory_id:8)
LineItem.create(order_id: 1, inventory_id:9)
LineItem.create(order_id: 1, inventory_id:10)
LineItem.create(order_id: 1, inventory_id:11)
LineItem.create(order_id: 1, inventory_id:2)
LineItem.create(order_id: 1, inventory_id:3)
LineItem.create(order_id: 1, inventory_id:4)
LineItem.create(order_id: 1, inventory_id:5)
LineItem.create(order_id: 1, inventory_id:6)
LineItem.create(order_id: 1, inventory_id:7)
LineItem.create(order_id: 1, inventory_id:8)
LineItem.create(order_id: 1, inventory_id:9)
LineItem.create(order_id: 1, inventory_id:10)
LineItem.create(order_id: 1, inventory_id:11)
